### ISSUE TITLE
Carousel image dialog padding is not consistent

### ISSUE THREAD

**Issue by Jupi007** [ubuntu-flutter-community/software#253]
The dialog is using material default padding which is `EdgeInsets.fromLTRB(0.0, 12.0, 0.0, 16.0)`, and it looks weird:

![image](https://user-images.githubusercontent.com/36476595/191608785-b932d938-d9cc-42c3-84bd-b84f68a167e9.png)

Imo, we should either remove the padding:

![Capture d’écran du 2022-09-21 22-59-18](https://user-images.githubusercontent.com/36476595/191609349-b2cc0ebf-730e-43b6-b6ae-f6b96b3855d2.png)

Or add the same one for each edge:

![Capture d’écran du 2022-09-21 22-59-33](https://user-images.githubusercontent.com/36476595/191609353-fcc71d45-aaa3-4b04-932f-de4310f7fc37.png)

_Sorry, I don't know why, but I can't load any image in the app_

CC @Feichtmeier

**Comment by Feichtmeier** [comment]
snap store is currently in maintenance

**Comment by Jupi007** [comment]
Oh, okay. _I was thinking it was my internet connexion which was completely broken 😅_

Sleep well 🌜

**Comment by Feichtmeier** [comment]
@Jupi007 I think this is fixed? Or maybe I did not understand it correctly

**Comment by Jupi007** [comment]
The look has changed since my first message but I think it is still the same problem :)

Imo, this dialog should look like this:

![image](https://user-images.githubusercontent.com/36476595/202844767-78997f29-7987-4d91-8161-80faefff5597.png)

- No titlebar, just the close button ;
- same padding on top, bottom and around the close button ;
- same margin as padding on top of the carousel place indicator.

I created a branch if you want to test: `Jupi007/issue253`

**Comment by Feichtmeier** [comment]
Thanks! Feel free to create a pull request

Or should we add a border property to the titleBar first?

**Comment by Jupi007** [comment]
> Or should we add a border property to the titleBar first?

I think we can, but it is not necessary for this as we just want a close button :)

> Thanks! Feel free to create a pull request

Okay 🚀
